name: build

on:
  push:
    branches: master
  pull_request:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docker:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.17]
    name: Test on Go ${{ matrix.go-version }} and OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:        
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Build
        run: make build

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build And Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386, linux/amd64, linux/arm64, linux/arm/v6, linux/arm/v7
          push: true
          tags: rlaskowski/myip:latest


      
